### PR TITLE
Remove zero-checksum heuristic

### LINKED ISSUE #391: Bad ZeroChecksum heuristics
Do we still need heuristics for bad ZeroChecksum implementation? I had case when `a.sendZeroChecksum` flag was incorrectly toggled after few consecutive packets were lost. Could we remove it completely, or disable it by default?

### PR DESCRIPTION
**Pull request by drshrey**
#### Description

Remove the legacy interop heuristic that toggled sendZeroChecksum after repeated RTOs with no TSN progress. Confirmed legacy interop is no longer needed and the flip ends up prolonging loss with newer version peers that don't have the bad zero checksum interpretation logic (where it would assume Zero Checksum Acceptable parameter meant it would receive zero checksum data).

#### Reference issue
https://github.com/pion/sctp/issues/391

Fixes #391

### CODE REVIEW

File: association.go [hunk 1]
```diff
@@ -270,6 +271,12 @@ type Config struct {
 	MaxReceiveBufferSize uint32
 	MaxMessageSize       uint32
 	EnableZeroChecksum   bool
+	// EnableLegacyZeroChecksumInterop enables a legacy interop fallback: when an
+	// association experiences repeated retransmission timeouts without TSN progress,
+	// alternate between sending DATA with and without checksums. Default is false;
+	// enable only when interoperating with legacy peers known to mis-handle
+	// ZeroChecksum negotiation.
+	EnableLegacyZeroChecksumInterop bool
```
Comment (JoTurk) [inline association.go]: what is the purpose of this flag and how are we going to use it from webrtc? can we just remove it all together?
